// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/dNationCloud/provider-gridscale/apis/ssl/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Loadbalancer.
func (mg *Loadbalancer) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ForwardingRule); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ForwardingRule[i3].CertificateUUID),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.ForwardingRule[i3].CertificateUUIDRef,
			Selector:     mg.Spec.ForProvider.ForwardingRule[i3].CertificateUUIDSelector,
			To: reference.To{
				List:    &v1alpha1.CertificateList{},
				Managed: &v1alpha1.Certificate{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ForwardingRule[i3].CertificateUUID")
		}
		mg.Spec.ForProvider.ForwardingRule[i3].CertificateUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ForwardingRule[i3].CertificateUUIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ListenIPv4UUID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ListenIPv4UUIDRef,
		Selector:     mg.Spec.ForProvider.ListenIPv4UUIDSelector,
		To: reference.To{
			List:    &IPv4List{},
			Managed: &IPv4{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ListenIPv4UUID")
	}
	mg.Spec.ForProvider.ListenIPv4UUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ListenIPv4UUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ListenIPv6UUID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ListenIPv6UUIDRef,
		Selector:     mg.Spec.ForProvider.ListenIPv6UUIDSelector,
		To: reference.To{
			List:    &IPv6List{},
			Managed: &IPv6{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ListenIPv6UUID")
	}
	mg.Spec.ForProvider.ListenIPv6UUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ListenIPv6UUIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.ForwardingRule); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ForwardingRule[i3].CertificateUUID),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.InitProvider.ForwardingRule[i3].CertificateUUIDRef,
			Selector:     mg.Spec.InitProvider.ForwardingRule[i3].CertificateUUIDSelector,
			To: reference.To{
				List:    &v1alpha1.CertificateList{},
				Managed: &v1alpha1.Certificate{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ForwardingRule[i3].CertificateUUID")
		}
		mg.Spec.InitProvider.ForwardingRule[i3].CertificateUUID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ForwardingRule[i3].CertificateUUIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ListenIPv4UUID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ListenIPv4UUIDRef,
		Selector:     mg.Spec.InitProvider.ListenIPv4UUIDSelector,
		To: reference.To{
			List:    &IPv4List{},
			Managed: &IPv4{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ListenIPv4UUID")
	}
	mg.Spec.InitProvider.ListenIPv4UUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ListenIPv4UUIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ListenIPv6UUID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ListenIPv6UUIDRef,
		Selector:     mg.Spec.InitProvider.ListenIPv6UUIDSelector,
		To: reference.To{
			List:    &IPv6List{},
			Managed: &IPv6{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ListenIPv6UUID")
	}
	mg.Spec.InitProvider.ListenIPv6UUID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ListenIPv6UUIDRef = rsp.ResolvedReference

	return nil
}
