// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Filesystem) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Firewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IPv4) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IPv6) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Isoimage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *K8S) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Loadbalancer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Network) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Server) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Snapshot) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Sshkey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Storage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Template) Hub() {}
