apiVersion: gridscale.crossplane.io/v1alpha1
kind: IPv4
metadata:
  name: ipv4-test
spec:
  forProvider:
    name: test-ipv4
    failover: true
    timeouts: 
      create: "1m"
  providerConfigRef:
    name: default
