apiVersion: gridscale.crossplane.io/v1alpha1
kind: Sshkey
metadata:
  name: sshkey-test
spec:
  forProvider:
    name: test-sshkey
    sshkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQPuRe1Z/WiG1399QQ0zePbpVo7INnH4C16mdjysABJ someexamplekey
    labels:
    - test
  providerConfigRef:
    name: default
