apiVersion: gridscale.crossplane.io/v1alpha1
kind: K8S
metadata:
  annotations:
    meta.upbound.io/example-id: gridscale/v1alpha1/k8s
  labels:
    testing.upbound.io/example-name: k8s-test
  name: k8s-test
spec:
  forProvider:
    name: test
    nodePool:
    - cores: 2
      memory: 4
      name: pool-0
      nodeCount: 2
      storage: 30
      storageType: storage_insane
    - cores: 1
      memory: 3
      name: pool-1
      nodeCount: 3
      storage: 30
      storageType: storage_insane
    release: "1.30"
