apiVersion: gridscale.crossplane.io/v1alpha1
kind: Loadbalancer
metadata:
  annotations:
    meta.upbound.io/example-id: gridscale/v1alpha1/loadbalancer
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    algorithm: leastconn
    backendServer:
    - host: ${gridscale_ipv4.server.ip}
      weight: 100
    forwardingRule:
    - listenPort: 80
      mode: http
      targetPort: 80
    labels: []
    listenIpv4UuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb
    listenIpv6UuidSelector:
      matchLabels:
        testing.upbound.io/example-name: lb
    name: test-lb
    redirectHttpToHttps: false
    timeouts:
    - create: 10m
