apiVersion: gridscale.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: gridscale/v1alpha1/server
  labels:
    testing.upbound.io/example-name: terra-server-test
  name: terra-server-test
spec:
  forProvider:
    cores: 2
    ipv4Selector:
      matchLabels:
        testing.upbound.io/example-name: terra-ipv4-test
    isoimage: 9be3e0a3-42ac-4207-8887-3383c405724d
    memory: 1
    name: terra-server-test
    network:
    - bootdevice: true
      objectUuidSelector:
        matchLabels:
          testing.upbound.io/example-name: terra-network-test
    - objectUuidSelector:
        matchLabels:
          testing.upbound.io/example-name: terra-network-test-2
    storage:
    - objectUuidSelector:
        matchLabels:
          testing.upbound.io/example-name: terra-storage-test
    timeouts:
    - create: 10m
